syntax on         		" 语法高亮
set number        		" 显示行号
set smartindent   		" 智能缩进
set autoindent    		" 自动对齐
set tabstop=4     		" tab缩进
set shiftwidth=4  		" 设定自动缩进为4个字符
set expandtab     		" 用space替代tab的输入
set mouse=a       		" 使用鼠标
set sm!           		" 高亮显示匹配括号
set cursorline    		" 高亮显示当前行